# Created by MisterBasic, Do not redistribute!!!
# 
# https://github.com/MisterBasic/GoldenEyes
# https://www.spigotmc.org/resources/authors/misterbasic.479098/
# 
# This is your configuration file :D


plugin:
  prefix: §8[§6GoldenEyes§8]§e
  config-version: 1
  debug: false
options:
  kick: true
  actionbar: true
  actionbar-message: §eThis server is protected by GoldenEyes AntiCheat
checks:
  autoclicker:
    enabled: true
    maxcps: 15
    maxcpskick: 30
  reach:
    enabled: true
    maxdistance: 4
  fastplace:
    enabled: true
    maxblocks: 15
  fastbow:
    enabled: true
  waterwalk:
    enabled: true
  autosneak:
    enabled: true
  liquidinteract:
    enabled: true
  flight:
    enabled: true
  antikb:
    enabled: true
  inventorycleaner:
    enabled: true
  xray:
    enabled: false
  speed:
    enabled: true
  badpackets:
    enabled: true
  antivpn:
    enabled: true
    blockedhosts:
    - ARETI-AS
    - EGIHostings
    - EGIHosting
    - anchorfree
    - Netherlands
    - NFORCE
    - Leaseweb
    - M247
    - PLI-AS
    - HostUS
    - IOMART-AS
    - WideOpenWest
    - Choopa
chat-manager:
  enabled: false
  blocked-words:
  - Unicorns_and_ponies
