# Created by MisterBasic, Do not redistribute! #

plugin:
  prefix: §8[§6GoldenEyes§8]§e
  config-version: 1
  debug: false
options:
  kick: true
  actionbar: true
  actionbar-message: §eThis server is protected by GoldenEyes AntiCheat
checks:
  autoclicker:
    enabled: true
    maxcps: 15
    maxcpskick: 30
  reach:
    enabled: true
    maxdistance: 4
  fastplace:
    enabled: true
    maxblocks: 15
  fastbow:
    enabled: true
  waterwalk:
    enabled: true
  autosneak:
    enabled: true
  liquidinteract:
    enabled: true
  flight:
    enabled: true
  antikb:
    enabled: true
  xray:
    enabled: false
  speed:
    enabled: false
  fastladder:
    enabled: false
  badpackets:
    enabled: false
  antiVPN:
    enabled: true
    blockedhosts:
    - EGIHostings
    - EGIHosting
    - anchorfree
    - Netherlands
    - Leaseweb
    - M247
    - PLI-AS
    - Choopa
    - HostUS
    - NFORCE
    - IOMART-AS
    - WideOpenWest
    - ARETI-AS
